### PR TITLE
chore: modernize module

### LINKED ISSUE #63: canvas.encode() does not work with Deno 1.40.4 or later.
This occurs when the following code is executed with Deno 1.40.4 or later.

```
import { createCanvas } from "https://deno.land/x/skia_canvas@0.5.5/mod.ts"
const canvas = createCanvas(100, 100)
canvas.encode("png")
```

Returning this error.

```
error: (in promise) TypeError: getBuffer is not a function
    const buffer = new Uint8Array(getBuffer(bufptr, 0, size));
                                  ^
    at Canvas.encode (https://deno.land/x/skia_canvas@0.5.4/src/canvas.ts:141:35)
```

Since Deno 1.40.4, many functions in `Deno[Deno.internal].core.ops` seem to be unavailable.

```
> Deno[Deno.internal].core.ops
{
  op_napi_open: [Function: op_napi_open],
  op_npm_process_state: [Function: op_npm_process_state],
  op_set_exit_code: [Function: op_set_exit_code],
  op_pledge_test_permissions: [Function: op_pledge_test_permissions],
  op_restore_test_permissions: [Function: op_restore_test_permissions],
  op_register_test: [Function: op_register_test],
  op_register_test_step: [Function: op_register_test_step],
  op_test_event_step_wait: [Function: op_test_event_step_wait],
  op_test_event_step_result_ok: [Function: op_test_event_step_result_ok],
  op_test_event_step_result_ignored: [Function: op_test_event_step_result_ignored],
  op_test_event_step_result_failed: [Function: op_test_event_step_result_failed],
  op_test_op_sanitizer_collect: [Function: op_test_op_sanitizer_collect],
  op_test_op_sanitizer_finish: [Function: op_test_op_sanitizer_finish],
  op_test_op_sanitizer_report: [Function: op_test_op_sanitizer_report],
  op_test_op_sanitizer_get_async_message: [Function: op_test_op_sanitizer_get_async_message]
}
```

### PR DESCRIPTION
**Pull request by lino-levan**
Closes #63 and #62

### CODE REVIEW

**Comment by RuiNtD** [comment]
It may be a good idea to [migrate the deps to JSR](https://jsr.io/docs/migrate-x-to-jsr) now that it's out. [Plug](https://jsr.io/@denosaurs/plug) appears to be on there.

**Comment by lino-levan** [comment]
@DjDeveloperr what do you think?

**Comment by DjDeveloperr** [comment]
I talked to Elias about it - we need some changes in plug before we can migrate: some additional utilities need to be exported, which we can simply import on deno.land/x but on JSR it needs to be explicitly specified as an entry point, or exported from the main entry point.

**Comment by lino-levan** [comment]
We could always vendor them, but if you're against that we can just sit tight.

**Review by DjDeveloperr — APPROVED** [review]
LGTM, thanks!
I added JSR support myself, and about the base64 encoding perf regression, we can look into optimizing later.
