### ISSUE TITLE
Does not load on Ubuntu

### ISSUE THREAD

**Issue by m0ose** [DjDeveloperr/skia_canvas#54]
This library did not work on Ubuntu 22.04, and probably other versions of Ubuntu.
```
import { createCanvas } from "https://deno.land/x/skia_canvas@0.5.2/mod.ts";
```
```
Uncaught TypeError: Deno.dlopen is not a function
    at dlopen (https://deno.land/x/plug@1.0.0-rc.3/mod.ts:145:15)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async https://deno.land/x/skia_canvas@0.5.2/src/ffi.ts:961:10
```

**Comment by DjDeveloperr** [comment]
Did you pass the unstable flag?

**Comment by m0ose** [comment]
I was not using the unstable flag. 
The unstable flag seems to have removed that error. Thank you. 

There is a different error now, which may be more related to my machine. It seems like I am missing a library or have the wrong version GLIBC. 
```Uncaught Error: Could not open library: Could not open library: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32'```

**Comment by DjDeveloperr** [comment]
What version of Ubuntu are you using? Only reason I can think of is old OS version. Try upgrading.

**Comment by m0ose** [comment]
I updated deno to version 1.33.1 and it seems to work fine. 

Thank you for your help.
